/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking_system;

import dataBase.connection;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohammad Adnan
 */
public class creat_account extends javax.swing.JFrame {

    /**
     * Creates new form CreatAccount
     */
    Random randome = new Random();
    int rAccNo = randome.nextInt(100000);
    int rPassword = randome.nextInt(100, 999);

    public creat_account() {
        initComponents();
    
        accNoTextField4.setText("" + rAccNo + 1);
        passwordTextField1.setText("" + rPassword + 1);
        ButtonGroup genderBtnGroup = new ButtonGroup();
        genderBtnGroup.add(maleRadioButton2);
        genderBtnGroup.add(femaleRadioButton1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        MainDesign = new javax.swing.JPanel();
        bankingManagementText = new javax.swing.JLabel();
        passwordTextField1 = new javax.swing.JTextField();
        ammountTextField2 = new javax.swing.JTextField();
        nameTextField3 = new javax.swing.JTextField();
        accNoTextField4 = new javax.swing.JTextField();
        phNoTextField5 = new javax.swing.JTextField();
        nameText = new javax.swing.JLabel();
        accTypeText = new javax.swing.JLabel();
        accNoText = new javax.swing.JLabel();
        phNoText = new javax.swing.JLabel();
        passwordText = new javax.swing.JLabel();
        ammoounttext = new javax.swing.JLabel();
        genderText = new javax.swing.JLabel();
        femaleRadioButton1 = new javax.swing.JRadioButton();
        maleRadioButton2 = new javax.swing.JRadioButton();
        accTypeComboBox1 = new javax.swing.JComboBox<>();
        creatButton1 = new javax.swing.JButton();
        backButton2 = new javax.swing.JButton();
        addresstext1 = new javax.swing.JLabel();
        addressTextField3 = new javax.swing.JTextField();
        nationalityTextField6 = new javax.swing.JTextField();
        phNoText1 = new javax.swing.JLabel();
        dobText2 = new javax.swing.JLabel();
        dateOfBirthChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banking Management System");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setToolTipText("");
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainDesign.setBackground(new java.awt.Color(255, 255, 255));
        MainDesign.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Creat Account", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Simplified Arabic Fixed", 1, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        MainDesign.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainDesign.setEnabled(false);
        MainDesign.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bankingManagementText.setFont(new java.awt.Font("AbakuTLSymSans", 1, 24)); // NOI18N
        bankingManagementText.setForeground(new java.awt.Color(255, 102, 102));
        bankingManagementText.setText("Banking System");
        MainDesign.add(bankingManagementText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        passwordTextField1.setEditable(false);
        passwordTextField1.setBackground(new java.awt.Color(241, 241, 250));
        MainDesign.add(passwordTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 190, -1));

        ammountTextField2.setBackground(new java.awt.Color(241, 241, 250));
        ammountTextField2.setForeground(new java.awt.Color(204, 204, 204));
        ammountTextField2.setText("1000-1000000...");
        ammountTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ammountTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ammountTextField2FocusLost(evt);
            }
        });
        ammountTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ammountTextField2ActionPerformed(evt);
            }
        });
        MainDesign.add(ammountTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 190, -1));

        nameTextField3.setBackground(new java.awt.Color(241, 241, 250));
        nameTextField3.setForeground(new java.awt.Color(204, 204, 204));
        nameTextField3.setText("abcd");
        nameTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextField3FocusLost(evt);
            }
        });
        nameTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextField3ActionPerformed(evt);
            }
        });
        MainDesign.add(nameTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 190, -1));

        accNoTextField4.setEditable(false);
        accNoTextField4.setBackground(new java.awt.Color(241, 241, 250));
        accNoTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainDesign.add(accNoTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 190, -1));

        phNoTextField5.setBackground(new java.awt.Color(241, 241, 250));
        phNoTextField5.setForeground(new java.awt.Color(204, 204, 204));
        phNoTextField5.setText("+123456789");
        phNoTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        phNoTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phNoTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phNoTextField5FocusLost(evt);
            }
        });
        phNoTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phNoTextField5ActionPerformed(evt);
            }
        });
        MainDesign.add(phNoTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 190, -1));

        nameText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameText.setText("Name: ");
        MainDesign.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, 27));

        accTypeText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        accTypeText.setText("Account Type:");
        MainDesign.add(accTypeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, 27));

        accNoText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        accNoText.setText("Accout  NO:");
        MainDesign.add(accNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, 27));

        phNoText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        phNoText.setText("Phone No:");
        MainDesign.add(phNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, 27));

        passwordText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordText.setText("Password:");
        MainDesign.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, 27));

        ammoounttext.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ammoounttext.setText("Ammount:");
        MainDesign.add(ammoounttext, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, 30));

        genderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        genderText.setText("Gender:");
        MainDesign.add(genderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, 27));

        femaleRadioButton1.setText("Female");
        femaleRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        femaleRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButton1ActionPerformed(evt);
            }
        });
        MainDesign.add(femaleRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, -1, -1));

        maleRadioButton2.setText("Male");
        maleRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maleRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButton2ActionPerformed(evt);
            }
        });
        MainDesign.add(maleRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        accTypeComboBox1.setBackground(new java.awt.Color(241, 241, 250));
        accTypeComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Current", "Saving" }));
        accTypeComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accTypeComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accTypeComboBox1ActionPerformed(evt);
            }
        });
        MainDesign.add(accTypeComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 190, -1));

        creatButton1.setBackground(new java.awt.Color(255, 51, 255));
        creatButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        creatButton1.setForeground(new java.awt.Color(255, 255, 255));
        creatButton1.setText("Creat");
        creatButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creatButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatButton1ActionPerformed(evt);
            }
        });
        MainDesign.add(creatButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 190, 40));
        creatButton1.getAccessibleContext().setAccessibleName("btn_Creat");

        backButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backButton2.setText("Back");
        backButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });
        MainDesign.add(backButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 190, 40));
        backButton2.getAccessibleContext().setAccessibleName("btn_Back");

        addresstext1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addresstext1.setText("Address:");
        MainDesign.add(addresstext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, 27));

        addressTextField3.setBackground(new java.awt.Color(241, 241, 250));
        addressTextField3.setForeground(new java.awt.Color(204, 204, 204));
        addressTextField3.setText("block A,street no 3");
        addressTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        addressTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressTextField3FocusLost(evt);
            }
        });
        MainDesign.add(addressTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 190, -1));

        nationalityTextField6.setBackground(new java.awt.Color(241, 241, 250));
        nationalityTextField6.setForeground(new java.awt.Color(204, 204, 204));
        nationalityTextField6.setText("Country Name");
        nationalityTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nationalityTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nationalityTextField6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nationalityTextField6FocusLost(evt);
            }
        });
        nationalityTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityTextField6ActionPerformed(evt);
            }
        });
        MainDesign.add(nationalityTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 190, -1));

        phNoText1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        phNoText1.setText("Nationality:");
        MainDesign.add(phNoText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, 27));

        dobText2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dobText2.setText("Date Of Birth");
        MainDesign.add(dobText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, 27));

        dateOfBirthChooser1.setBackground(new java.awt.Color(241, 241, 250));
        dateOfBirthChooser1.setName("dateOfBirthChooser1"); // NOI18N
        MainDesign.add(dateOfBirthChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 190, -1));

        Background.add(MainDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 1000, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void createAccount(String name, String accNo, String password, String phNo, String accType, String gender, String address, String nationality, String dateOfBirth, String ammount) {
        
        try {

            try ( Connection con = connection.connect()) {
                PreparedStatement pst;
                String insertQuery = "INSERT INTO `users` (`name`, `account_no`, `password`, `phone_no`, `account_type`, `gender`, `address`, `nationality`, `balance`, `date_of_birth`) VALUES "
                        + "("
                        + "'" + name + "',"
                        + "'" + accNo + "',"
                        + "'" + password + "',"
                        + "'" + phNo + "',"
                        + "'" + accType + "',"
                        + "'" + gender + "',"
                        + "'" + address + "',"
                        + "'" + nationality + "',"
                         + "'" + ammount + "',"
                        + "'" + dateOfBirth + "'"
                        + ")";
                pst = con.prepareStatement(insertQuery);
                pst.execute();
                con.close();

                //store transactions
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSSSSS");
                String formattedDate = formatter.format(LocalDateTime.now());

                String type = "Account Creation time";
                storeTransactions(accNo, "System", "System", name, accNo, ammount, formattedDate, type);

                Icon icon = new javax.swing.ImageIcon(getClass().getResource("/asset/icons/person.png"));
                JOptionPane.showMessageDialog(rootPane, "Account Created Successfully", "Account Creation", JOptionPane.OK_OPTION, icon);
            }
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(rootPane, "Something went worng!", "Account Creation", HEIGHT);
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void storeTransactions(String user_id, String from_ac, String from_name, String to_name, String to_ac, String ammount, String date, String payment_type) {
        try {

            try ( Connection con = connection.connect()) {
                PreparedStatement pst;

                String insertQuery = "INSERT INTO users_transactions (user_id, to_name, to_ac, from_ac, from_name,ammount, payment_type, date) VALUES "
                        + "("
                        + "'" + user_id + "',"
                        + "'" + to_name + "',"
                        + "'" + to_ac + "',"
                        + "'" + from_ac + "',"
                        + "'" + from_name + "',"
                        + "'" + ammount + "',"
                        + "'" + payment_type + "',"
                        + "'" + date + "'"
                        + ")";
                pst = con.prepareStatement(insertQuery);
                pst.execute();
                con.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Something went worng!", "Account Creation", HEIGHT);
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void accTypeComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accTypeComboBox1ActionPerformed

    }//GEN-LAST:event_accTypeComboBox1ActionPerformed

    private void nameTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextField3FocusGained
        if (nameTextField3.getText().equals("abcd")) {
            nameTextField3.setText("");
            nameTextField3.setForeground(Color.black);
        }
    }//GEN-LAST:event_nameTextField3FocusGained

    private void nameTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextField3FocusLost
        if (nameTextField3.getText().equals("")) {
            nameTextField3.setText("abcd");
            nameTextField3.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_nameTextField3FocusLost

    private void phNoTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phNoTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phNoTextField5ActionPerformed

    private void phNoTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phNoTextField5FocusGained
        if (phNoTextField5.getText().equals("+123456789")) {
            phNoTextField5.setText("");
            phNoTextField5.setForeground(Color.black);
        }
    }//GEN-LAST:event_phNoTextField5FocusGained

    private void phNoTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phNoTextField5FocusLost
        if (phNoTextField5.getText().equals("")) {
            phNoTextField5.setText("+123456789");
            phNoTextField5.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_phNoTextField5FocusLost

    private void ammountTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ammountTextField2FocusGained
        if (ammountTextField2.getText().equals("1000-1000000...")) {
            ammountTextField2.setText("");
            ammountTextField2.setForeground(Color.black);
        }
    }//GEN-LAST:event_ammountTextField2FocusGained

    private void ammountTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ammountTextField2FocusLost
        if (ammountTextField2.getText().equals(" ")) {
            ammountTextField2.setText("1000-1000000...");
            ammountTextField2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_ammountTextField2FocusLost

    private void addressTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTextField3FocusGained

        if (addressTextField3.getText().equals("block A,street no 3")) {
            addressTextField3.setText("");
            addressTextField3.setForeground(Color.black);
        }
    }//GEN-LAST:event_addressTextField3FocusGained

    private void addressTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTextField3FocusLost
        if (addressTextField3.getText().equals(" ")) {
            addressTextField3.setText("block A,street no 3");
            addressTextField3.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_addressTextField3FocusLost

    private void nameTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextField3ActionPerformed

    }//GEN-LAST:event_nameTextField3ActionPerformed

    private void ammountTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ammountTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ammountTextField2ActionPerformed

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_backButton2ActionPerformed

    private void creatButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatButton1ActionPerformed
        String name = "", phNo = "", address = "", ammount = "", accType = "", gender = "", nationality = "", dateOfBirth = "";

        if (!"abcd".equals(nameTextField3.getText())) {
            name = nameTextField3.getText();
        }
        String password = passwordTextField1.getText();
        String accNo = accNoTextField4.getText();
        if (!"+123456789".equals(phNoTextField5.getText())) {
            phNo = phNoTextField5.getText();
        }
        // String accType = accTypeComboBox1;
        if (!"block A,street no 3".equals(addressTextField3.getText())) {
            address = addressTextField3.getText();
        }
        if (!"1000-1000000...".equals(ammountTextField2.getText())) {
            ammount = ammountTextField2.getText();
        }

        if (maleRadioButton2.isSelected()) {
            gender = "male";
        } else if (femaleRadioButton1.isSelected()) {
            gender = "Female";
        }
        accType = accTypeComboBox1.getSelectedItem().toString();
        if (!("Country Name").equals(nationalityTextField6.getText())) {
            nationality = nationalityTextField6.getText();
        }
        if (dateOfBirthChooser1.getDate() != null) {

            Date selectedDate = dateOfBirthChooser1.getDate();
            LocalDate localDate = LocalDate.ofInstant(selectedDate.toInstant(), ZoneId.systemDefault());
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            dateOfBirth = formatter.format(localDate);

        }

        if (!"".equals(name) && !"".equals(phNo) && !"".equals(address) && !"".equals(ammount) && !"".equals(accType) && !"".equals(gender) && !"".equals(nationality) && !"".equals(dateOfBirth)) {

            createAccount(name, accNo, password, phNo, accType, gender, address, nationality, dateOfBirth, ammount);
             this.dispose();
        new login().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please fill all the fields", "Account Creation", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_creatButton1ActionPerformed

    private void maleRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButton2ActionPerformed

    }//GEN-LAST:event_maleRadioButton2ActionPerformed

    private void femaleRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButton1ActionPerformed

    }//GEN-LAST:event_femaleRadioButton1ActionPerformed

    private void nationalityTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nationalityTextField6FocusGained
        if ("Country Name".equals(nationalityTextField6.getText())) {
            nationalityTextField6.setText("");
            nationalityTextField6.setForeground(Color.black);
        }
    }//GEN-LAST:event_nationalityTextField6FocusGained

    private void nationalityTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nationalityTextField6FocusLost
        if ("".equals(nationalityTextField6.getText())) {
            nationalityTextField6.setText("Country Name");
            nationalityTextField6.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_nationalityTextField6FocusLost

    private void nationalityTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(creat_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new creat_account().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel MainDesign;
    private javax.swing.JLabel accNoText;
    private javax.swing.JTextField accNoTextField4;
    private javax.swing.JComboBox<String> accTypeComboBox1;
    private javax.swing.JLabel accTypeText;
    private javax.swing.JTextField addressTextField3;
    private javax.swing.JLabel addresstext1;
    private javax.swing.JLabel ammoounttext;
    private javax.swing.JTextField ammountTextField2;
    private javax.swing.JButton backButton2;
    private javax.swing.JLabel bankingManagementText;
    private javax.swing.JButton creatButton1;
    private com.toedter.calendar.JDateChooser dateOfBirthChooser1;
    private javax.swing.JLabel dobText2;
    private javax.swing.JRadioButton femaleRadioButton1;
    private javax.swing.JLabel genderText;
    private javax.swing.JRadioButton maleRadioButton2;
    private javax.swing.JLabel nameText;
    private javax.swing.JTextField nameTextField3;
    private javax.swing.JTextField nationalityTextField6;
    private javax.swing.JLabel passwordText;
    private javax.swing.JTextField passwordTextField1;
    private javax.swing.JLabel phNoText;
    private javax.swing.JLabel phNoText1;
    private javax.swing.JTextField phNoTextField5;
    // End of variables declaration//GEN-END:variables
}
