/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking_system;

import dataBase.connection;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Mohammad Adnan
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form BankingManagementSystem
     */
    public login() {
        initComponents();
      
    }

    private static boolean login(String accNo, String password) {
        try {

            Connection con = connection.connect();
            PreparedStatement pst;
            ResultSet rs;
            String sqlQuery = "SELECT * from users WHERE account_no =? AND password = ? ";
            pst = con.prepareStatement(sqlQuery);
            pst.setString(1, accNo);
            pst.setString(2, password);
            rs = pst.executeQuery();

            return rs.next();

        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        MainDesign = new javax.swing.JPanel();
        bankingMangementText = new javax.swing.JLabel();
        logInText = new javax.swing.JLabel();
        accNoText = new javax.swing.JLabel();
        accNoIcon = new javax.swing.JLabel();
        passwordIcon = new javax.swing.JLabel();
        accNoTextField2 = new javax.swing.JTextField();
        passwordTextField1 = new javax.swing.JTextField();
        passwordText = new javax.swing.JLabel();
        logInButton1 = new javax.swing.JButton();
        CreatAccButton2 = new javax.swing.JButton();
        dontHaveAccText = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setLocation(new java.awt.Point(0, 0));

        jPanel4.setBackground(new java.awt.Color(44, 71, 158));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Creat Account", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Simplified Arabic Fixed", 1, 18))); // NOI18N
        jPanel2.setEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 71, 158));
        jLabel9.setText("Banking Management System");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/images/bank_78392.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 140, 140));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(241, 241, 250));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 190, -1));

        jTextField4.setBackground(new java.awt.Color(241, 241, 250));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 190, -1));

        jTextField5.setBackground(new java.awt.Color(241, 241, 250));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 190, -1));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(241, 241, 250));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 190, -1));

        jTextField7.setBackground(new java.awt.Color(241, 241, 250));
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 190, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText("Name: ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, 27));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setText("Account Type:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, 27));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setText("Accout  NO:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, 27));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel14.setText("Phone No:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, 27));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setText("Password:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, 27));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel16.setText("Address:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, 27));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel17.setText("Gender:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, 27));

        jRadioButton1.setText("Female");
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jRadioButton2.setText("Male");
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(241, 241, 250));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Current", "Saving" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 190, -1));

        jButton3.setBackground(new java.awt.Color(0, 204, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Creat");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 60, -1));

        jButton4.setText("Back");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 60, -1));

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Clear");
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 60, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 670, 420));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel18.setText("Accout  NO:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 153, -1, 27));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel19.setText("Phone No:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 192, -1, 27));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel20.setText("Password:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 231, -1, 27));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banking Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setForeground(new java.awt.Color(44, 71, 158));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainDesign.setBackground(new java.awt.Color(255, 255, 255));
        MainDesign.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MainDesign.setPreferredSize(new java.awt.Dimension(670, 420));
        MainDesign.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bankingMangementText.setFont(new java.awt.Font("AbakuTLSymSans", 1, 24)); // NOI18N
        bankingMangementText.setForeground(new java.awt.Color(255, 102, 102));
        bankingMangementText.setText("Banking System");
        MainDesign.add(bankingMangementText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        logInText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        logInText.setForeground(new java.awt.Color(255, 51, 255));
        logInText.setText("LOG IN");
        MainDesign.add(logInText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        accNoText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        accNoText.setText("Account Number");
        MainDesign.add(accNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        accNoIcon.setBackground(new java.awt.Color(0, 0, 0));
        accNoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons/acc_no.png"))); // NOI18N
        MainDesign.add(accNoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 20, 40));

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons/password.png"))); // NOI18N
        MainDesign.add(passwordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        accNoTextField2.setBackground(new java.awt.Color(241, 241, 250));
        accNoTextField2.setForeground(new java.awt.Color(204, 204, 204));
        accNoTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                accNoTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                accNoTextField2FocusLost(evt);
            }
        });
        accNoTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accNoTextField2MouseEntered(evt);
            }
        });
        accNoTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNoTextField2ActionPerformed(evt);
            }
        });
        MainDesign.add(accNoTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 210, 40));
        accNoTextField2.getAccessibleContext().setAccessibleName("acc_no");

        passwordTextField1.setBackground(new java.awt.Color(241, 241, 250));
        passwordTextField1.setForeground(new java.awt.Color(204, 204, 204));
        passwordTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTextField1FocusLost(evt);
            }
        });
        MainDesign.add(passwordTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 210, 40));
        passwordTextField1.getAccessibleContext().setAccessibleName("password");

        passwordText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        passwordText.setText("Password");
        MainDesign.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        logInButton1.setBackground(new java.awt.Color(255, 51, 255));
        logInButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logInButton1.setForeground(new java.awt.Color(255, 255, 255));
        logInButton1.setText("Login");
        logInButton1.setBorder(null);
        logInButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logInButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logInButton1.setMargin(new java.awt.Insets(2, 14, 30, 14));
        logInButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButton1ActionPerformed(evt);
            }
        });
        MainDesign.add(logInButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 210, 30));
        logInButton1.getAccessibleContext().setAccessibleName("btn_login");

        CreatAccButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CreatAccButton2.setForeground(new java.awt.Color(255, 51, 255));
        CreatAccButton2.setText("Creat Account");
        CreatAccButton2.setBorder(null);
        CreatAccButton2.setContentAreaFilled(false);
        CreatAccButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreatAccButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatAccButton2ActionPerformed(evt);
            }
        });
        MainDesign.add(CreatAccButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 80, 20));
        CreatAccButton2.getAccessibleContext().setAccessibleName("btn_c_acc");

        dontHaveAccText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dontHaveAccText.setText("Dont't have account?");
        MainDesign.add(dontHaveAccText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, 20));

        Background.add(MainDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void CreatAccButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatAccButton2ActionPerformed
        this.dispose();
        new creat_account().setVisible(true);
    }//GEN-LAST:event_CreatAccButton2ActionPerformed

    private void logInButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButton1ActionPerformed
        String accNo = "", password = "";
        Boolean checker = true;
        accNo = accNoTextField2.getText();
            password = passwordTextField1.getText();
        if (!"".equals(accNo) && !"".equals(password)) {
            if (login.login(accNo, password)) {

                checker = false;
                this.dispose();
                home homeObject = new home(accNo);
                homeObject.setVisible(true);
            }
            if (checker) {
                JOptionPane.showMessageDialog(rootPane, "Account Number / Password\nis invalid!", "Account Login", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Please fill all the fields", "Account Login", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_logInButton1ActionPerformed

    private void passwordTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextField1FocusLost

    }//GEN-LAST:event_passwordTextField1FocusLost

    private void passwordTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextField1FocusGained

    }//GEN-LAST:event_passwordTextField1FocusGained

    private void accNoTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNoTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accNoTextField2ActionPerformed

    private void accNoTextField2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accNoTextField2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_accNoTextField2MouseEntered

    private void accNoTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accNoTextField2FocusLost
      
    }//GEN-LAST:event_accNoTextField2FocusLost

    private void accNoTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accNoTextField2FocusGained
      
    }//GEN-LAST:event_accNoTextField2FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton CreatAccButton2;
    private javax.swing.JPanel MainDesign;
    private javax.swing.JLabel accNoIcon;
    private javax.swing.JLabel accNoText;
    private javax.swing.JTextField accNoTextField2;
    private javax.swing.JLabel bankingMangementText;
    private javax.swing.JLabel dontHaveAccText;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton logInButton1;
    private javax.swing.JLabel logInText;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JLabel passwordText;
    private javax.swing.JTextField passwordTextField1;
    // End of variables declaration//GEN-END:variables
}
